# Generated by Django 4.1.1 on 2022-09-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripbegin', '0005_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attraction',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
