# Generated by Django 3.2 on 2022-10-10 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tripbegin', '0006_delete_attraction_delete_review_delete_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingType', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel')], max_length=6)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=35)),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tripbegin.flight')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tripbegin.hotel')),
            ],
        ),
    ]
