# Generated by Django 3.2 on 2022-10-10 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripbegin', '0008_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
